import html

def render_healing_stepper(collector_id_escaped: str, current_step: int) -> str:
    """Render HTML stepper timeline component representing healing state progress."""
    return f"""
    <div class="kintsugi-stepper" id="stepper-{collector_id_escaped}">
        <div class="step-segment {'active' if current_step >= 1 else ''}">
            <span class="step-dot"></span>
            <span class="step-label">Detected</span>
        </div>
        <div class="step-segment {'active' if current_step >= 2 else ''}">
            <span class="step-dot"></span>
            <span class="step-label">Healing</span>
        </div>
        <div class="step-segment {'active' if current_step >= 3 else ''}">
            <span class="step-dot"></span>
            <span class="step-label">Awaiting Approval</span>
        </div>
        <div class="step-segment {'active' if current_step >= 4 else ''}">
            <span class="step-dot"></span>
            <span class="step-label">Committed</span>
        </div>
    </div>
    """

def render_pending_heal(collector_id_escaped: str, pending_data: dict) -> str:
    """Render HTML pending review container with selector modifications diff."""
    diff_summ = html.escape(pending_data.get("diff_summary", ""))
    prev_res = html.escape(pending_data.get("preview_result", ""))
    msg = html.escape(pending_data.get("message", ""))
    explanation = pending_data.get("explanation", "")
    
    explanation_html = ""
    if explanation:
        explanation_html = f"""
        <div class="heal-explanation-box" style="margin-top:12px; margin-bottom:12px; padding:12px; background:rgba(212, 175, 55, 0.08); border-left:3px solid var(--accent-gold); border-radius:4px; font-size:0.92em; line-height:1.45; text-align:left;">
            <div style="font-weight:600; color:var(--accent-gold); margin-bottom:4px;">💡 Explainable AI-Healing (Generated by Gemini)</div>
            <div style="color:var(--text-muted);">{html.escape(explanation)}</div>
        </div>
        """
    
    return f"""
    <div class="heal-preview-panel visible">
        <div class="heal-preview-title"><svg style='width:1.2em;height:1.2em;vertical-align:-0.2em;display:inline-block;' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z'></path></svg> Awaiting Approval — Review the proposed repair below</div>
        {f'<div class="heal-diff-summary">{diff_summ}</div>' if diff_summ else ''}
        {explanation_html}
        {f'<div class="heal-preview-result">{prev_res}</div>' if prev_res else ''}
        {f'<div class="heal-preview-result">{msg}</div>' if msg and not prev_res else ''}
        <button class="heal-approve-btn" data-action="approve-heal" data-collector="{collector_id_escaped}">
            <svg style='width:1.2em;height:1.2em;vertical-align:-0.2em;display:inline-block;' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 13l4 4L19 7'></path></svg> <span class="btn-text">Approve & Commit Repair</span>
        </button>
        <div class="heal-status-msg">Heal will not take effect until approved.</div>
    </div>
    """
